### ISSUE TITLE
https://twitter.github.io/scala_school/ lost its styling

### ISSUE THREAD

**Issue by stefanlance** [twitter/scala_school#204] opened 2018-04-17 23:34 UTC
https://github.com/twitter/scala_school/pull/202 was recently merged, after which I pulled from master and ran `make publish`, as the readme says. This deployed the latest version of the site except it lost all its styling in production. 

**Steps to reproduce:**
- request write access to this repository
- clone master and ensure the dependencies listed in the readme are installed
- run `make serve` to see the local site with the proper styling
- run `make publish` to see the production site without the styling

**Comment by vincentfree** [comment] 2018-05-19 07:49
@akanshmurthy you could already make a pull request right?

**Comment by vincentfree** [comment] 2018-05-19 07:55
Looks like he isn't done yet, the homepage is ok but the rest still lacks styling

**Comment by taverasmisael** [comment] 2018-10-21 15:15
@akanshmurthy I've seen across Github some repos with bots to manage claiming issues with commands like Slack (```/request```, for example) and not leading anyone who was not assigned to PR on this issue. If the person does not respond in a determined time the issue is _reseted_ and is open to being reassigned. I think we could implement one here 😉

**Comment by taverasmisael** [comment] 2018-10-21 15:17
@vincentfree I saw the #205 PR and the problem relayed on he fixing only the main layout, I noticed this and changed the path for styles on all of them on my #211 as you can see in the GH is on my forked repo

**Closed** 2018-10-22 18:52 UTC
